import * as fs from 'fs';
import * as path from 'path';
import { randomUUID } from 'crypto';

/**
 * The web UI's own lightweight run-history log — NOT a duplicate of the
 * existing reporting system (JUnit/HTML/Allure, still generated by the
 * real Playwright run every execution already goes through). Those
 * reports describe the SINGLE most recent run and get overwritten every
 * time; there is no existing multi-run, per-application history anywhere
 * in the engine to "reuse" for the Applications/Test History dashboards
 * this UI's spec asks for, so this is new, UI-only persistence — one
 * small JSON file the UI backend appends to after each execution it
 * drives. It never touches discovery/generation/execution/coverage
 * logic itself.
 */
export type RunStatus = 'running' | 'passed' | 'failed' | 'cancelled';

export interface HistoryEntry {
  id: string;
  timestamp: string;
  application: string;
  requirementText: string;
  stableTestId?: string;
  /** The live-execution runId (live-events.ts) — present on every entry
   *  created via startRun; used by updateRun to find the row to update.
   *  Optional only because older history files predate this field. */
  runId?: string;
  status: RunStatus;
  passedCount: number;
  total: number;
  durationMs: number;
}

const HISTORY_PATH = path.resolve(process.cwd(), 'reports', 'gap-ui-history.json');

function readAll(): HistoryEntry[] {
  if (!fs.existsSync(HISTORY_PATH)) return [];
  try {
    return JSON.parse(fs.readFileSync(HISTORY_PATH, 'utf-8')) as HistoryEntry[];
  } catch {
    return [];
  }
}

function writeAll(entries: HistoryEntry[]): void {
  fs.mkdirSync(path.dirname(HISTORY_PATH), { recursive: true });
  fs.writeFileSync(HISTORY_PATH, `${JSON.stringify(entries, null, 2)}\n`, 'utf-8');
}

export function record(entry: Omit<HistoryEntry, 'id' | 'timestamp'>): HistoryEntry {
  const full: HistoryEntry = { ...entry, id: randomUUID(), timestamp: new Date().toISOString() };
  const all = readAll();
  all.push(full);
  writeAll(all);
  return full;
}

/**
 * Recorded the instant a live execution is spawned (see routes.ts's
 * runExecutionJob) — status 'running', 0/0 — so Test History shows a run
 * in progress immediately, not only after it finishes. updateRun below
 * mutates this SAME row (matched by runId) rather than appending a second
 * one, so a run always occupies exactly one history row start to finish.
 */
export function startRun(entry: {
  runId: string;
  application: string;
  requirementText: string;
  stableTestId?: string;
}): HistoryEntry {
  const full: HistoryEntry = {
    ...entry,
    id: randomUUID(),
    timestamp: new Date().toISOString(),
    status: 'running',
    passedCount: 0,
    total: 1,
    durationMs: 0,
  };
  const all = readAll();
  all.push(full);
  writeAll(all);
  return full;
}

export function updateRun(
  runId: string,
  patch: Partial<Pick<HistoryEntry, 'status' | 'passedCount' | 'total' | 'durationMs'>>,
): HistoryEntry | undefined {
  const all = readAll();
  const entry = all.find((e) => e.runId === runId);
  if (!entry) return undefined;
  Object.assign(entry, patch);
  writeAll(all);
  return entry;
}

/** Newest first — what the Test History table displays. */
export function listAll(): HistoryEntry[] {
  return readAll().sort((a, b) => b.timestamp.localeCompare(a.timestamp));
}

export function forApplication(application: string): HistoryEntry[] {
  return listAll().filter((e) => e.application === application);
}

export interface ApplicationSummary {
  lastStatus?: RunStatus;
  lastRunAt?: string;
  totalRuns: number;
  passRate: number;
}

export function summaryFor(application: string): ApplicationSummary {
  const runs = forApplication(application);
  if (runs.length === 0) return { totalRuns: 0, passRate: 0 };
  // Pass rate is computed over FINISHED runs only — a run still 'running'
  // (or 'cancelled', which never produced a pass/fail verdict) would
  // otherwise silently drag the rate down while it's still in flight.
  const finished = runs.filter((r) => r.status === 'passed' || r.status === 'failed');
  const passed = finished.filter((r) => r.status === 'passed').length;
  return {
    lastStatus: runs[0].status,
    lastRunAt: runs[0].timestamp,
    totalRuns: runs.length,
    passRate: finished.length === 0 ? 0 : Math.round((passed / finished.length) * 100),
  };
}
